js/trackCore.js

restores FusionJuncSpan rendering

FusionJuncSpan is the type and the format

---

.idea/.name
.idea/misc.xml
.idea/modules.xml
dev/juncspan-dev.html
js/feature/featureParsers.js
js/feature/featureTrack.js

fusion arc line thickness based on read support.

improved visualization of fusion junc

---

js/bam/bamAlignment.js

The popup looks like
(from: http://exac.broadinstitute.org/variant/2-71738895-G-GGGCAGTGGTCCGAT)

Added insertion summary popup

---

css/igv.css
js/igv-create.js

Pull request for this issue: https://github.com/igvteam/igv.js/issues/223

Toggle Karyotype Panel - Issue #223

---

js/browser.js
js/feature/aneuSource.js
js/feature/aneuTrack.js
js/feature/featureFileReader.js
js/igv-utils.js
js/igvxhr.js
js/trackCore.js
js/ui/dragAndDrop.js

Generalize `igvxhr.loadString()` to support both local file and url.

Refactor igvxhr loadString function

---

dev/wig.html
js/feature/wigTrack.js
js/trackCore.js
js/trackView.js
js/ui/colorpicker.js
js/ui/dataRangeDialog.js

Functions moved from trackCore.js to trackView.js to allow JuiceboxJS trackRenderer to use track menus.

TrackCore and TrackView changes to support JuiceboxJS Track Menus

---

dev/igv-dev.html
js/browser.js

Git Issue 256. Tracks not redrawn when window resized.

Git Issue 256. Tracks not redrawn when window resized.

---

js/browser.js
js/trackCore.js

Git Issue 201. API to remove track by name.

Git Issue 201. API to remove track by name.

---

js/variant/variantTrack.js

Don't present group-by if sampleInformation not loaded

---

dev/igv-dev.html
js/feature/featureTrack.js

Fix Y-Offset Bug in FeatureTrack

Fix Y-Offset Bug in FeatureTrack

---

dev/encode-dev.html
js/ui/igvModalTable.js

IGV Modal Table API Update. More generalized.

IGV Modal Table API Update. More generalized.

---

js/rulerSweeper.js

Git Issue 428. Wonky ruler sweeper. Ruler sweeper mousedown event fixes.

Git Issue 428. Wonky ruler sweeper.

---

js/feature/featureTrack.js

The description doesn't seem to be called every time it's clicked only when the track is first loaded, so I put the information for all color-by options in the description since it wouldn't update based on the color-by property.

Snp feature track description and color-by in track menu

---

dev/igv-dev.html
dev/shared-js.html
js/igv-math.js
js/rulerTrack.js

Better Ruler Label Placement and Legibility

Better Ruler Label Placement and Legibility

---

examples/igv-modal-table.html
examples/js/igv-modal-table.js
js/encode/encodeDataSource.js

IGV Modal Table Example. Updates.

IGV Modal Table Example. Updates.

---

examples/1kg-vcf.html
examples/api.html
examples/bam.html
examples/beta.html
examples/copyNumber.html
examples/dropbox.html
examples/ga4gh.html
examples/google-demo.html
examples/modal-table-example.html

Updated Examples

---

js/ui/popover.js

Disable Popover dragging.

---

js/ui/colorpicker.js
js/ui/dataRangeDialog.js
js/ui/dialog.js
js/ui/popover.js

Only disable dialog dragging in JuiceboxJS.

Only disable dialog dragging in JuiceboxJS.

---

js/bam/bamReader.js
js/bam/bamUtils.js
js/bam/bamWebserviceReader.js

Typos, missing semicolons, extra docs, try to normalise use of "" and ''.
I think everything can be squashed in one commit but left individual commits for now. Please let me know if you want me to squash everything into one commit before merge and will do it.
Thanks!

Small fixes

---

js/browser.js
js/igv-create.js

Git issue 405. Bug fix. Locus search no longer increments locus start.

Git issue 405. Bug fix. Locus search no longer increments locus start.

---

examples/js/modalTable.js
js/encode/encodeDataSource.js
js/igvxhr.js

Background load ENCODE Modal Table Data. In support of JuiceboxJS Git Issue 196.

Background load ENCODE Modal Table Data. In support of JuiceboxJS Git Issue 196.

---

Gruntfile.js
dev/igv-dev.html
js/igv-create.js
js/trackView.js
js/ui/dataRangeDialog.js
js/ui/dialog.js
js/ui/popover.js
vendor/jquery-ui.js

igvjs now bundles jquery-ui

---

js/igv-create.js
js/trackCore.js
js/ui/dataRangeDialog.js
js/ui/dialog.js
js/ui/popover.js

Discard unneeded igv.colorPicker={}

Discard unneeded igv.colorPicker={}

---

examples/js/modal-table-example.js
examples/js/modalTable.js
examples/modal-table-example.html
js/encode/encodeDataSource.js
js/igv-create.js

Refactor encodetable construction.

Refactor encodetable construction.

---

js/igv-color.js
js/igv-math.js

Add back removed color and utility functions.

Add back removed color and utility functions.

---

dev/igv-dev.html
js/feature/wigTrack.js
js/ui/dataRangeDialog.js

Autoscale is now set to false if user manually sets data range.

DataRange. Autoscale is now set to false if user manually sets data range.

---

.gitignore
dev/gtex.html
js/bam/bamTrack.js
js/browser.js
js/igv-create.js
js/rulerSweeper.js
js/ui/chromosomeSelectWidget.js
js/viewport.js

browser.search function now works again.

browser.search function now works again.

---

dev/igv-dev.html
js/feature/wigTrack.js
js/trackView.js

Wig track data range issue. Now using trackView.setDataRange when toggling autoscale.

Wig track data range issue. Now using trackView.setDataRange when toggling autoscale.

---

js/browser.js

Git Issue 510. Single Base Locus Goto now works properly.

Git Issue 510. Single Base Locus Goto now works properly.

---

js/ga4gh/ga4ghHelper.js

This is a follow up to my last PR to use the standard oauth features for ga4gh where one can provide a function that resolves to a token.

Use standard oauth features for ga4gh

---

dev/igv-dev.html
js/browser.js

Bug fix. locus = all now works.

Bug fix. locus = all now works.

---

js/browser.js
js/rulerSweeper.js

Bug fix. Ruler Sweeper.

---

js/viewport.js

Refactor track panel handlers. Now hosted in viewport.

Refactor track panel handlers. Now hosted in viewport.

---

dev/igv-dev.html
js/trackView.js
js/viewport.js

Repair Track AutoHeight.

---

js/browser.js

Browser edits related to track pan handler refactor. They got lost along the way during merge/rebase/etc.

Browser edits related to track pan handler refactor.

---

js/bam/bamTrack.js
js/browser.js
js/feature/mergedTrack.js
js/igv-create.js
js/referenceFrame.js
js/rulerTrack.js

With this removal genomicState contains only a referenceFrame and locusSearchString.

Remove chromosome property from genomicState object.

---

css/igv.scss

center .igv-search-container correctly

---

js/bam/bamTrack.js

Add base count display by strand on popupData (#547)

---

js/bam/bamTrack.js
js/feature/featureSource.js
js/feature/featureTrack.js
js/igv-create.js
js/trackCore.js

Support visibility window. Add visibility window track gear menu.

Support visibility window. Add visibility window track gear menu.

---

js/bigwig/bwReader.js
test/testAED.js
test/testBAM.js
test/testBigwig.js

I had trouble seeing my tests run, because other failing tests prevented their execution.
- fixed a bug in bwReader
- "fixed" BAM test (does not even attempt operation that is destined to fail)
- fixed bigwig test

Making sure that the AED tests run

---

js/feature/featureParsers.js
test/testAED.js

I am terribly sorry, two bugs skipped past me as I did a last minute pull from your repo.
These are both fixed.

Bug fixes after merge

---

dev/localGenome.html

Genome JSON Loading Bug

---

dev/localGenome.html

Revert "Genome JSON Loading Bug"

---

js/gtex/gtex.js

Update GTEx tissue info Web Service API Call.

Update GTEx tissue info Web Service API Call.

---

test/js/test.js

Update to latest GTEx API

---

js/gtex/gtex.js
test/js/test.js

GTEx Track Configuration Function

GTEx Track Configuration Function

---

js/ui/alertDialog.js

AlertDialog.js. Now accepts html string.

AlertDialog.js. Now accepts html string.

---

js/igvxhr.js

xhr.onload() - getAccessToken(). Refactor. Call reject with error.

xhr.onload() - getAccessToken(). Refactor. Call reject with error.

---

js/igvxhr.js

Revert "xhr.onload() - getAccessToken(). Refactor. Call reject with error."

---

dev/igv-dev.html
dev/js/dev.js

dev.js. repair gtex service access.

dev.js. repair gtex service access.

---

js/igv-create.js

Git issue 718. ShowControls config now works properly.

Git issue 718. ShowControls config now works properly.

---

js/igv-create.js
test/testBrowser.js

Fix Show Navigation bug.

---

js/bam/alignmentBlock.js

Fix was provided for baseAt(), this PR does the same change for qualityAt()

issue544Fix:related change

---

js/browser.js
js/trackCore.js
js/viewport.js

Track Labels. handle multi-locus view.

Track Labels. handle multi-locus view.

---

dev/localGenome.html
js/browser.js
js/rulerTrack.js

Genome swap bug. Show/hide ruler bug is the real culprit

Genome swap bug. Show/hide ruler bug is the real culprit

---

js/bam/bamTrack.js
js/feature/segTrack.js

Track Render Fixes Specific to SVG Output.

Track Render Fixes Specific to SVG Output.

---

dev/svg.html
js/browser.js

SVG Save. API signature improvements.

SVG Save. API signature improvements.

---

js/bam/bamTrack.js

Fix rounding error in bam coverage, where Math.floor was used without correcting the input.

Correct rounding error in bam coverage calculation

---

js/viewport.js

Git Issue 765. SVG Axis Rendered only for first panel in multi-locus.

Git Issue 765. SVG Axis Rendered only for first panel in multi-locus.

---

js/browser.js
js/canvas2svg.js
js/ideogram.js
js/viewport.js

Git Issue 765. SVG Render. Multi-locus view. Inter-panel gap.

Git Issue 765. SVG Render. Multi-locus view. Inter-panel gap.

---

js/feature/wigTrack.js
js/viewport.js

SVG Render. WIG Track. X value is NaN.

SVG Render. WIG Track. X value is NaN.

---

js/bam/bamTrack.js
js/feature/featureTrack.js

Track Gear Horizontal Line Fixes

Track Gear Horizontal Line Fixes

---

wrapper/embedCss.js

embedCss.js edits

---

dev/igv-track-container-div-hierarchy.html
js/browser.js
js/igv-create.js
js/viewport.js

This fixes a bug that caused repeated recreation of the track popover during either search or mult-panel.

Bug fix (Issue 783). Viewport deletion did not delete popover.

---

dev/igv-dev.html
js/browser.js

Bug fix: Multi-locus was not appearing when multiple loci were specified on config.

Bug fix: Multi-locus was not appearing.

---

dev/cursor_guide.html
js/browser.js
js/igv-utils.js
js/ui/cursorGuide.js
js/viewport.js

CursorGuide. Custom mouse handler.

CursorGuide. Custom mouse handler.

---

css/igv.css
css/igv.scss
js/browser.js

Navbar tweaks. SVG filename change.

Navbar tweaks. SVG filename change.

---

js/feature/featureFileReader.js

bug fix. undefined variable.

---

js/feature/featureSource.js

bug fix - featureSource.

---

js/util/domUtils.js
js/viewport.js

Render Track Labels to SVG

---

js/api.js

api.js additions

---

js/viewport.js

Bug Fix. Save Track to SVG Not Working #983.

Bug Fix. Save Track to SVG Not Working #983.

---

js/viewport.js

SVG save. Track labels now have backgrounds.

SVG save. Track labels now have backgrounds.

---

js/viewport.js

Track Label SVG Treaks

---

js/api.js
package-lock.json

Add download to api.js

---

js/version.js
js/viewport.js

SVG save bug fix. Git issue 1009.

SVG save bug fix. Git issue 1009.

---

js/viewport.js

Git Issue 1014. SVG Rendering bug fix.

Git Issue 1014. SVG Rendering bug fix.

---

js/browser.js

Adding API to removeROI

---

dev/igv-dev.html
js/browser.js
js/igv-create.js
js/ui/cursorGuide.js
js/version.js
js/viewport.js
package-lock.json

Git Issue 1035. Also bug fix for cursorGuide.js for multi-locus.

Git Issue 1035. Also bug fix for cursorGuide.js for multi-locus.

---

dev/custom-cursor-guide.html
dev/igv-dev.html
js/ui/cursorGuide.js
js/version.js
js/viewport.js

Repair CursorGuide Mouse Handler

Repair CursorGuide Mouse Handler

---

js/trackBase.js
js/viewport.js

Check https://github.com/igvteam/igv.js/issues/1018

Adding ability to set custom track description

---

js/ui/menuUtils.js
js/version.js

MenuUtils. API change: handleClick(e)

MenuUtils. API change: handleClick(e)

---

js/trackView.js
js/version.js
package-lock.json

ColorPicker presentation positioning tweak

ColorPicker presentation positioning tweak

---

dev/svg-dev.html
js/browser.js
js/ui/svgSaveControl.js
js/viewport.js

Render SVG Edits

---

js/browser.js
js/trackView.js

Bug fix. DOM element create/destroy.

Bug fix. DOM element create/destroy.

---

js/browser.js
js/trackFactory.js
test/testBrowser.js

allow browser instance to add tracks to TrackFactory

---

js/bam/bamTrack.js

Add option to show/hide coverage/alignment track #1106

Add option to show/hide coverage/alignment track #1106

---

dev/igv-dev.html
js/ideogramTrack.js
js/ideogramViewport.js
js/viewport.js
js/viewportBase.js
package-lock.json

IdeogramViewport method signatures

IdeogramViewport method signatures

---

js/ui/alertDialog.js

Alert dialog positioning fix.

---

.github/workflows/ci_build.yml
.travis.yml
README.md

Switching from Travis CI to GitHub Actions

GitHub Actions

---

README.md

fix maf example url in readme

---

js/bam/bamAlignmentRow.js
js/bam/bamTrack.js

* Add new sorting option by aligned read length
* This corresponds to https://github.com/igvteam/igv/pull/1159/ in igv java

Sort by aligned read length

---

js/CNVpytor/HDF5_Reader.js
js/CNVpytor/MeanShiftUtil.js
js/CNVpytor/cnvpytorTrack.js
js/CNVpytor/t_dist.js

Updated the cnvpytor track for the following. 
- Removed the dependency for https://cdn.jsdelivr.net/gh/stdlib-js/constants-float64-e@v0.0.8-esm/index.mjs
- Added naive javascript implementation for t distribution's CDF.

cnvpytor track update

---

js/cnvpytor/CombinedCaller.js
js/cnvpytor/GeneralUtil.js
js/cnvpytor/HDF5IndexedReader.js
js/cnvpytor/MeanShiftUtil.js
js/cnvpytor/cnvpytorTrack.js
js/cnvpytor/cnvpytorVCF.js
js/cnvpytor/t_dist.js

Updates for the CNVpytor track
-  For Pytor file as input:
Available bin sizes are being added from both read depth and BAF signal
- For VCF file as input:
2D caller is introduced

Update for CNVpytor track

---

js/browser.js
js/roi/ROIManager.js
js/sample/sampleInfoViewport.js
js/trackView.js

ROI and SampleInfo SVG Rendering Implemented

---

dev/misc/png.html
js/browser.js
package.json
test/utils/forceESM.cjs
test/utils/mockObjects.js

Add functionality to save igvjs browser display as PNG file.

git issue 1665 png output

---

dev/htsget/htsget-umccr-cram.html
js/htsget/htsgetCramReader.js
js/htsget/htsgetReader.js

PR to continue @brainstorm 's work on CRAM support in htsget

WIP for HtsgetCRAM

---

js/cnvpytor/HDF5IndexedReader.js
js/cnvpytor/cnvpytorVCF.js

The following bug fixes and updates were implemented. 
- VCF file as input: A bug fix during histogram creation.
- pytor file as input: Utilizing the baf i1 signal for baf likelihood to reduce memory usage.
- Added docs for few cnvpytor track related class/functions 
-- Arijit

cnvpytor track: Updates

---

js/roi/ROIManager.js
js/roi/ROITable.js

Toggle only ROI background. Leave header intact.

Toggle only ROI background. Leave header intact.

---

js/feature/mergedTrack.js
js/trackView.js
js/ui/dataRangeDialog.js

DataRange Dialog bug fix for MergedTrack usage

DataRange Dialog Bug Fix

---

dev/sampleInfo/vcf.html
dev/wig/popover-numbers.html
js/feature/wigTrack.js
js/sample/sampleInfoControl.js
js/sample/sampleInfoViewport.js
js/sample/sampleNameControl.js
js/sample/sampleNameViewport.js
js/trackViewport.js

- Better display of genomic and numerical data in track popup
- Repair sampleName column hide/show
-

Misc. To do list tasks

---

dev/sampleInfo/combined.html
js/feature/segTrack.js
js/sample/sampleInfo.js
js/sample/sampleInfoViewport.js
js/variant/variantTrack.js

Sample Info now displays properly with multiple tracks and sample-info files. Attribute tiles now align properly with respect to the track they are associated with.

Sample Info Display Repair

---

dev/sampleInfo/combined.html
dev/sampleInfo/sampleInfo.html
dev/sampleInfo/sampleInfo2.html
dev/sampleInfo/sampleInfoTestRig.html
dev/sampleInfo/vcf.html
js/browser.js
js/sample/sampleInfo.js

Bug fix: Adding additional sampletable file was not repainting the associated sampleInfo tiles.

SampleInfo repaint issue

---

js/roi/ROIManager.js
js/roi/ROIMenu.js
js/roi/ROISet.js

Add copy & blat sequence to ROI menu

Use menu frame for ROI menu
