igvteam/igv.js

js/set.js
Phantomjs 2.0.0 was mislead by the way checking of Set object was done. This is a most standard way for checking existence of an Object that works across browsers.
=> Improve checking of Set object

js/bam/bamAlignment.js, js/igv-create.js
Proposed fix for two minor bugs:
1. Calling `decodeTags()` in `bamAlignment` could get into an infinite loop for unsupported types since `p` is not incremented. The fix just returns whatever tags have been decoded since there's no way to continue.
2. The way `true` default is applied on `config.showNavigation` makes it impossible to set a false value.
=> Fixing minor bugs

doc/events.html, js/browser.js, js/feature/featureTrack.js
Our app's users had the same feature request as is described in #185 so I figured it might be useful. 
These changes introduce the following:
- FeatureTrack's label rendering now accounts for the visible window when determining the label position. The label is now centered within the visible portion of feature.
- FeatureTrack's labels are repainted after track dragging stops - in my testing the dragging remains smooth.
- To enable this behavior I've added `trackdrag` and `trackremoved` events.
I did have one concern - do you think it's appropriate for FeatureTrack to reference its FeatureView's Tile object?
=> Feature label visibility

css/igv.css, js/browser.js, js/igv-create.js
The changelist introduces a centered vertical line that can be enabled using `showVerticalLine = true` browser config #137. Additionally, the line may be anchored to the cursor if `showVerticalLine = "sticky"` is set #131.
The line itself is just a border on an absolutely positioned DIV within the contentDiv. Its appearance can easily be styled using CSS and it avoids any additional canvas repainting.
=> Vertical guide line implementation

js/igv-create.js
This line would be enough to make the version number accessible from the "developer tools console" available in modern browsers.
This would be useful when debugging a website and trying to work out which version of IGV.js is being used.
=> Expose Version Number Variable #220

js/browser.js
The original design is to use the first one when multiple search results found. But there were something wrong with the logic implemented in the code. 
@jrobinso Is there any update about the function presentSearchResults to allow user to choose?
Another thing is, I customized some parts of jgv.js for cBioPortal usage. There are few features added. We are thinking to send pull request back to igv team. May I know should I send pull request back to master or other branch?
=> bug fix about choosing first search result when multiple returned

js/bam/bamReader.js, js/igvxhr.js
Let me know what you think. I believe this should be sufficient to allow any track type (references, variants, etc) to support gs:// paths.
=> Support GCS paths for all track types. Fixes #271.

css/igv.css, js/igv-create.js
I changed it from "Show Karyotype/Hide Karyotype" to just "Karyotype".
It now uses the CSS classes "igv-nav-bar-toggle-button-off" and "igv-nav-bar-toggle-button-on" to change colours when clicked.
I also tweaked the CSS for .igv-nav-bar-toggle-button a little bit, to provide more consistent capitalisation and button width.
=> Made the toggle Karyotype button consistent with the other toggle buttons

js/feature/featureTrack.js
Feature clicking had a bug where it was using expandedCallHeight for tracks in SQUISHED mode, and squishedCallHeight for tracks in EXPANDED mode (would cause wrong feature popup to be displayed)
Same issue for the track_height resizing when toggling between EXPANDED and SQUISHED, was using wrong callHeight variable.
=> bug with squished/expanded click/track_resize

js/bam/bamIndex.js, js/bam/bamReader.js, js/bam/bgzf.js, js/bigwig/bufferedReader.js, js/bigwig/bwReader.js, js/feature/aneuSource.js, js/feature/aneuTrack.js, js/feature/featureFileReader.js, js/feature/tribble.js, js/hic/hicReader.js, js/igv-utils.js, js/igvxhr.js, js/tdf/tdfReader.js
The wiki page could look like this:
Files provided behind an OAuth secured endpoint need a bearer access token to be accessed. The bearer access token can be provided within the track definition in several ways:
1. As a function returning the token string itself or a promise:
```js
{
"name": "Phase 3 WGS variants",
"format": "vcf",
"url": "https://s3.amazonaws.com/1000genomes/release/20130502/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz",
"indexURL":  "https://s3.amazonaws.com/1000genomes/release/20130502/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5b.20130502.sites.vcf.gz.tbi",
"type": "variant",
"oauthToken": myOauthTokenFn
}
```
2. As a string or a promise:
```js
{
"name": "Phase 3 WGS variants",
"format": "vcf",
"url": …
```
=> Oauth support

js/variant/variant.js
This function can be simply replaced by `join()`,  by the way, **`1` was used as `i`**.
=> arrayToCommaString bug

js/bam/bamTrack.js, js/feature/featureTrack.js, js/feature/wigTrack.js, js/variant/variantTrack.js
Track gear menu. When running JuiceboxJS remove colorpicker menu item.
=> Track gear menu. When running JuiceboxJS remove colorpicker menu item.

js/bam/bamUtils.js
The current BAM spec doesn't support a cigar with >65535 operators. However, aligning ultra-long nanopore reads occasionally produces such alignments that can't be directly encoded in BAM. It will fail *all* released SAM=>BAM converters so far. [Minimap2](https://github.com/lh3/minimap2) has an option "-L" that moves a long cigar to a tag. A modified BAM reader can move the real cigar in the tag back to the right place on reading. This simple solution seamlessly solves the long-cigar issue. Users and most developers won't even notice this change.
This PR adds the long cigar support to igv.js. A working example can be found [at this page](http://lh3lh3.users.sourceforge.net/data/cigar-64k/igv-js-test/bam-lh3.html). It points to a read aligned with >72000 operators and displays it …
=> support CIGARs with >65535 operators

dev/bam.html, dev/igv-dev.html, examples/js/modal-table-example.js, examples/modal-table-example.html
This is a maintenance thing. Support for Inclusion of shared JS is going away in 2018 for - at least - Chrome browser.
=> Start removing shared.js from examples and dev.

js/ga4gh/ga4ghHelper.js
I was using this against a local GA4GH service and noticed that the Authorization header was not getting set on GET requests.   I only found some old GA4GH tests that may cover this change.   I was not sure if there was some other test I should verify here, but the change is pretty minor.
=>  Set headers for GA4GH GET requests

js/ideogram.js
I think it is better to do expensive operations only when you really must. My assumption is that changing canvas backing store size means the browser has to reallocate the entire canvas buffer, which really should be done only on resizes...
=> Only reinitialize canvas when resizing (#545)

js/browser.js
At app launch it is possible to pan and generate a completely bogus locus when results in not actual pan and the app in an unusable state. This is the fix.
=> Browser. Panning Bug Fix.

css/igv.scss, js/viewport.js
Fixes https://github.com/igvteam/igv.js/issues/634
I've also replace the bold text on hover by a subtle grey background. The reason is that the bold-text effect changes the label dimensions, which looks less clean.
=> Add title attribute on track labels

package.json
This enables including igv.js using ES6 `import` as done in modern React, Angular and Vue, while retaining support for AMD `require` and plain `script` tags, as discussed in #701.  
It also adds `scripts` and `files` properties to package.json to build igv.js artifacts before publishing to NPM, and to strip other files from the package.  And it puts metadata previously only visible in the published NPM package into source control, to be more open source and in line with mainstream JS conventions.
See the following for examples of various ways to include igv.js, using the experimental [tmp_es6_igv](https://www.npmjs.com/package/tmp_es6_igv) NPM package:
* [ES6 `import` in React](https://github.com/eweitz/igv.js-react), specifically …
=> Provide easily usable ES6 export, improve package metadata

package.json
The [package.json improvements](https://github.com/igvteam/igv.js/commit/0c551bb1dcfe3f062671d83ec055faf06acf471c) in #702 included adding `scripts` and `files` properties to package.json to build igv.js artifacts before publishing to NPM, and to strip other files from the package.  
While replying to [Jim's comment from yesterday](https://github.com/igvteam/igv.js/issues/701#issuecomment-411629051), it occurred to me that the `scripts` property could be refined.
This updates the `scripts` property to run Grunt during `npm pack`, in addition to `npm publish`.  It enables developers to preview what the igv NPM package will contain before publishing.
Using package.json has benefits over using external (e.g. Jenkins) build scripts: 1) it is open source (with all the benefits that brings), 2) …
=> Enable previewing NPM package via `npm pack`

js/igv-canvas.js
The save/restore pairs are quite slow especially in loops executing
thousands of times. Usually the save/restore is needed only when
properties are being set. For untransformed text drawing, a fast
path was added that draws text directly without save/transform/restore.
=> Avoid save/restore whenever possible

js/igv-create.js
There are 2 removeBrowser functions in igv-create.js, with the second one throwing an error upon usage. This function is needed as we are using virtual lists to render thousands of sequencing results and need to cleanup the browsers that are no longer in the view. (Though once we scroll through about 10 browsers, it still crashes)
=> Remove second removeBrowser function

dev/igv-dev.html, js/browser.js
show/hide ruler works again. New issue: multi-locus panel delete button. The ruler track houses the delete button when we are in multi-locus view. Can we do without the button when the ruler is not shown?
=> show/hide ruler works again. New issue: multi-locus panel delete button.

js/igvxhr.js
Fixes a problem when bundled within an ES6 react application:
```
ReferenceError: decodeUTF8 is not defined
at igv.esm.js:42783
at igv.esm.js:42221
at igv.esm.js:6
```
=> fixed decodeUTF8 function signature

js/trackView.js
Color picker event handling fix. Stop propagation. To support the juicebox colorpicker PR.
=> Color picker event handling fix. Stop propagation.

js/feature/featureTrack.js
Adds strand/direction (>/<) mark to all features.
Reverse strand must be explicitly specified. (previous implementation adds reverse if strand is not "+")
If nothing is specified no strand mark added.
=> show strand marks on all features

js/trackView.js
Specifying track color as a function works again, e.g.
var track_colour_test_wig = {
"type": "wig",
"name": "colour_test_wig",
"url": "data/colour_test.bedGraph.gz",
"min": 0,
"max": 5,
"color": function (x) { return "rgb(0,0,255)"; },
"height": 100
};
=> fix bug with using a function for track color

package-lock.json, package.json
This moves all normal dependencies to dev dependencies, since they are unused when importing IGV as a dependency. Of note, `@gmod/bam` and `shelljs` can be removed entirely without effecting anything, but that was outside the scope of this.
The reason for wanting to do this was the warnings being generated when I installed IGV as a dependency to my project, which doesn't use `grunt`:
```
npm WARN grunt-contrib-clean@2.0.0 requires a peer of grunt@>=0.4.5 but none is installed. You must install peer dependencies yourself.
npm WARN grunt-contrib-connect@2.0.0 requires a peer of grunt@>=0.4.0 but none is installed. You must install peer dependencies yourself.
```
This has no effect on the built output - aside from marking packages as `dev` in the package-lock, the only changes are the same …
=> Make all normal dependencies dev dependencies

js/feature/featureFileReader.js
it seems that the `await` operator is missing since `igvxhr.loadString` is async..
=> bug fix - await on igvxhr.loadString

js/feature/featureParsers.js
Unfortunately, 0 is false-y so the test was incorrectly failing to parse a legitimate feature.
Sorry, this came out only when I was doing a very thorough test, normally people have no features at 0.
=> AED allows a 0 for feature start.

js/igvxhr.js
I am getting ArrayBuffer from the response which has a convenient .slice method that is useful for this sort of situation.
Fixing issue #1049
=> Instead of erroring, provide slice of loaded data

dev/gcnv.html, js/feature/featureFileReader.js, js/gcnv/gcnvParser.js, js/gcnv/gcnvTrack.js, js/trackFactory.js, js/trackView.js
Track for displaying normalized coverage data generated by gCNV
The underlying data format is a modified .bed-like file with a tab-separated header row, follow by data rows with chrom, start, end fields followed by per-sample copy-number floating-point values like
```
chrom    start       end      sample1   sample2   sample3   
chr1     12345     54321        1.3        2.5        3    
chr1     55555     66666        1.0        2.1       1.2 
``` 
This file must be bgzip compressed and have a tabix index.
=> gCNV track

js/gcnv/gcnvTrack.js
this makes click / segment overlap calculations faster, and allows metadata about background samples to be hidden
=> added onlyHandleClicksForHighlightedSamples boolean config option 

js/browser.js
Just fixes a typo I came across when I specified an invalid genome.
=> Minor typo in unknown genome alert

js/viewport.js
We needed a way to create a custom variant reader and have a button to view more information in the popup dialog. This enables that by doing something like:
` fields.push({ html: '<button>Some button for this variant</button>'});`
as part of the `Variant.prototype.popupData` function in the custom reader.
Also, this "feature" would also get rid of the hardcoded checking for "<hr>". Although that does break compatibility for anyone who relied on this (no hurt in keep it there).
=> Allow HTML in the popover for variant custom reader

js/feature/textFeatureSource.js
I use igv js for displaying features in annotation-tracks via the `feature`-option. When a track-feature-list is empty an error dialog is displayed.
Example code:
```js
const config = {
reference: {
id: "my genome",
fastaURL: this.fastaUrl,
indexed: false,
tracks: [
{
name: "empty",
type: "annotation",
features: [],
}
],
wholeGenomeView: false
},
};
```
Error:
The error appears in the `FeatureCache` constructor, but is caused by not returning a list from `fixFeatures`. This patch fixes the `fixFeatures` method. It might also be an option to check if the `featurelist` object is `undefined` in the `FeatureCache`-constructor.
=> Fix bug: Empty text features list causes error

js/bam/alignmentContainer.js
Secondary alignments with no sequence stored in the bam/cram file (such as produced by minimap2) crash igv.js with ugly popup saying `Cannot read property 'charAt' of undefined`  and console showing 
```
viewport.js:222 TypeError: Cannot read property 'charAt' of undefined
at n (alignmentContainer.js:322)
at alignmentContainer.js:278
at Array.forEach (<anonymous>)
at ra.incCounts (alignmentContainer.js:277)
at ea.push (alignmentContainer.js:70)
at Ch.readAlignments (cramReader.js:170)
at async Ih.getAlignments (bamSource.js:103)
at async Fh.getFeatures (bamTrack.js:144)
at async Wr.getFeatures (viewport.js:557)
at async Wr.loadFeatures (viewport.js:201)
```
Example problematic sam line is:
```
7f6556bb-3235-42d9-8c17-b9c9d83328b2	256	chr11	1915532	0 …
```
=> Fix undefined variable when no seq stored in bam for a read

js/rulerViewport.js
Problem: After igv.js is closed, a setTimeout might trigger, which is then tying to read an undefined `$tooltip` property.
This PR checks if the `$tooltip` property is defined.
=> rulerViewport: check tooltip defined in mouseMove/setTimeout

js/bam/bamTrack.js, js/feature/interactionTrack.js, js/variant/variantTrack.js
- Remove from gear menu
- Show in context menu only when circular-viewer is displayed
-
=> Change 'show cords' in track menus

js/igv-create.js
bug fix - when loading the igv, if you don't provide an explicit `queryParametersSupported: false` in the options object, the igv iterates over current query parameters looking for parameters of certain names (like 'file') and appends them to the config. and if, by any chance, you have corruption in the url (like we had an accidental `&&` in the middle), the igv loading hangs the browser (goes into infinite loop). this simple fix solves this (if a query param is somehow invalid, move on to the next)
=> bug fix - IGV js hangs and crashes browser if something is "off" in the url

js/bam/bamTrack.js
As discussed in #1511 , allows a function to be specified for the `color` of an alignment track. Any more specific options will override that function.
The `default` in the switch statement was redundant as far as I could tell (and would have re-overwritten the color variable), and so I removed it here.
If this PR is merged, I agree to transfer the copyright of these changes to the copyright holders of the `igv.js` repository.
=> Allow color function for alignment

js/bam/bamTrack.js
addresses #1498 
Adds 4 new config options for alignment tracks:
* `insertionTextColor` (default: white)
* `showInsertionText` (default: false)
* `deletionTextColor` (default: black)
* `showDeletionText`: (default: false)
if both insertion and deletion text are shown via the above options, it may look something like this (example with CCS reads + HTT expansion; ignore the read colours):
there is also a bit of logic to decide when to stop drawing these labels when the user is zoomed out enough.
this also changes bases to be drawn on top of insertions/deletions to match the Java version. this can be reverted fairly easily if desired. gaps are now also drawn underneath insertions to display more intuitively.
If this PR is merged, I agree to transfer the copyright of these changes to the …
=> allow the display of insertion/deletion base counts

js/feature/wigTrack.js
Enable (smaller) partial reading of indexed wig-like files.  It's probably been a programming error to provide `windowFunction` instead of `visibilityWindow` to that funciton.
A different isssue: The UI for using tsv+bgzip+tabix for numerical data on arbitrary column is quite cumbersome. I managed with track:
```
{
name: this_track_name,
url: fname,
indexURL: fname + ".tbi",
order: track_idx,
type: "wig,
format: "gwas",
visibilityWindow: vis_window,
columns: {
chromosome: 1,
position: 2,
value: value_column
}
}
```
note `type="wig", format="gwas"`.  Plain `type="tsv"` would be nicer.
=> Add visibilityWindow for WigTrack

js/feature/mergedTrack.js
Updated the merged track for the following.
1. Added the option for global graphType and If global setting is not present, local track configuration works.
2. Bug fix for supportsWholeGenome. supportsWholeGenome is now not property not function. 
Thank you
Arijit
=> Local/global graphType  for mergedTrack and bugfix

js/feature/decode/ucsc.js, test/data/bed/gfftags.bed, test/testBED.js
The purpose of this patch is to honor the `nameField` configuration option when creating annotation tracks from BED files which use a `gffTags` name field.
=> use nameField when parsing BED files

js/feature/decode/ucsc.js, js/feature/gff/gff.js, test/data/bed/gfftags.bed, test/testBED.js, test/testGFF.js
This PR changes the behavior of BED `gffTags` attribute parsing, removing the character subset limits of the GFF3 spec in favor of URI-decoding all encoded values in the attributes. This mirrors the behavior of standalone IGV.
One additional change was made in order to also decode the attribute key (previously, only attribute value was decoded). The GFF3 spec makes no distinction between the two in discussions of encoding and escaping characters.
Several testing modifications were made to encompass these changes.
=> decode all URI-encoded BED attributes

js/feature/textFeatureSource.js
It's fix for https://github.com/igvteam/igv.js/issues/1609. 
For VCF from HTSGET source, only first query for some region get data from server. All subsequent requests try to get data from cahce, but cache not contains that data.
The reason of this behaviour: in textFeatureSource.js in loadFeatures method
```
const genomicInterval = this.queryable ?
new GenomicInterval(queryChr, intervalStart, intervalEnd) :
undefined
```
i.e. when later we put data into cache `genomicInterval` is `undefined`. In the cache, an `undefined` range value is interpreted as included all features.
=> Set queryable to true for HTSGET source

js/bam/alignmentContainer.js, js/bam/bamAlignmentRow.js, js/bam/bamTrack.js
Edited code so that :
When view as pairs, sorting will find the pairs that overlap the position,
when not view as pairs, sorting will find the single reads that overlap the position.
This behaviour is actually same as the IGV desktop version.
=> can sort as pairs when view as pairs, sort as single reads otherwise

js/feature/decode/interact.js
Hi,
I'm proposing a simple adjustment to the code for parsing interact file. 
The first two indices describing region of the interaction pair were parsed as strings which caused problems when rendering interaction pairs arcs in some cases.
Based on what I've tracked down in my usecase:
- when arc type is proportional, the `dataRange.max` is used to compute `yscale` (`interactionTrack.js` file). 
- The `max` defaulted to 0 even when viewing regions with defined interactions for some genomic positions, which caused the `igv.js` to not draw `proportional` arcs while `nested` arcs could be drawn. The behavior was further inconsistent as whether the arc was drawn was dependent on genomic position and zoom level.
- The underlying reason for this is that when computing the `dataRange.max`, the …
=> Parse start and end as numbers in interact file

js/bam/bamTrack.js
added setReadsToHighlight() method to AlignmentTrack
which can take an array of read names, then highlight the reads
for example :
`const bamTracks = browser.findTracks('type', 'alignment')`
`bamTracks[0].alignmentTrack.setReadsToHighlight(["readName1", "readName2"])`
`bamTracks[0].updateViews()`
also added 
"highlightedReadsOutlineColor" (optional) 
"readsToHighlight" (optional)
in Alignment Track options,
which allow configuration of the color of the highlighted reads,
and the configuration of the reads to highlight
for example:
`{`
`  type: "alignment",`
`  format: "bam",`
`  name: "NA12889",`
`  url: "gs://genomics-public-data/platinum-genomes/bam/NA12878_S1.bam",`
`  indexURL: "gs://genomics-public-data/platinum-genomes/bam/NA12878_S1.bam.bai",`
`  sort: {`
`    chr: "chr1",`
` …
=> added setReadsToHighlight() method to AlignmentTrack

js/cnvpytor/CombinedCaller.js, js/cnvpytor/HDF5IndexedReader.js, js/cnvpytor/cnvpytorTrack.js, js/cnvpytor/cnvpytorVCF.js
The following changes were made for the cnvpytor track code. 
1. To mitigate memory constraints when reading the entire VCF file, elements were purged from featureSource.reader.features during SNP processing. This action frees up memory following VCF file ingestion.
2. Improve code structure for `HDF5IndexedReader.js`
- Arijit
=> cnvpytor track: vcf input and structure

js/browser.js, js/roi/ROIManager.js
Fix ROI shift issue when saving svg:
Issue:
When the IGV browser is not stick to the left of the web page, the saved SVG will have the ROI shifted:
how the IGV place in the webpage:
the output SVG from IGV:
If the IGV browser is stick to the left of the webpage like this👇, then the ROI in SVG will be normal
Work around:
Minus the columnContainer's clientX when rendering SVG rect of ROI instead of just using the regionElement's clientX
=> fix ROI shift issue when saving svg

js/feature/mergedTrack.js, js/trackView.js
Fixes #1758. 
Fixes issue with negative values not being taken into account when autoscaling merged tracks.
=> Fix Merged track negative autoscaling

js/feature/wigTrack.js, js/roi/ROIManager.js
Fixed two minor bugs related to ROI and WIG tracks:
When adding custom ROI and trying to name it or switch to it the coordinates were not calculated properly for contigs with - (hyphen) in their name. 
**Example**: If we have _contig-example01-123-156_ the split will take _contig_ as the contig name and try to convert _example01_ to int for the starting locus.
Fixed by taking the last two elements of the split results as start and end and joining the rest with - and taking the result of that as a contig name.
There is a baseline drawn when there are negative values in WIG file(s). This baseline was not taking flip y-axis into consideration i.e. it was not being moved to a new position of 0 on Y axis.
Fixed by subtracting the ratio of height from 1 in case of a flipped Y axis.
---
Sorry …
=> Minor fixes ROI and WIG track

js/feature/mergedTrack.js
PR fixing issues in Merged track.
A number of things related to Merged track popup data have been fixed.
**Issue**: The popup data was showing all data points which were loaded and not just those the user clicked on i.e. the click on popup behaviour was not the same as it is in the individual WIG tracks. 
As you can see in the screenshot above the list is so long that it cannot fit into the popup when the track is zoomed out. In the screenshot below you can see how it looked like when zoomed in to the individual level. The position I clicked on is 1500 and instead of showing just that value it shows a lot of values around it.
**Fix**: Fixed by applying the clickedFeatures function logic on Merged track and adding the track name to the features list to make sure we pair the features with …
=> Merged track fixes/improvements

js/util/paintAxis.js
Change axis limit labelling so that small values (< 0.1) are displayed with exponential notation (e.g. "2.3e-3") instead of "0.00" as previously implemented.
This would fix #1800
=> Change prettyPrint for small numbers - see issue #1800

js/cnvpytor/cnvpytorTrack.js
The following updates have been made:
- Added a spinner image during the loading of a new bin size and cnv caller to enhance user experience.
- BAF Label: Negative numbers are now displayed as positive numbers. For example, the range 0 to -1 will now be displayed as 0 to 1.
Thank you,
Arijit
=> cnvpytor track update

js/genome/indexedFasta.js, test/testFasta.js
Hi! Thank you again for an awesome project!
I found one bug. It's not exactly a bug, since it only occurs if you disobey the documentation. Documentation doesn't mention this, but I found that - thanks to `igvxhr` - I can provide async functions for any URL in the config. However, if I set `fastaURL` as a function and omit `indexURL` and `indexFile`, IGV.js generates a `(function() {}).fai` gibberish URL.
I understand this isn't a typical bug because the documentation doesn't mention using functions for `fastaURL`. And, I know you wanted to reconsider the whole idea of guessing that URL. However, I wanted to fix this for consistency with track URLs and to add tests, so if you decide to change this behavior, it's test covered.
Feel free to request changes to this PR.
=> Guess Fasta `indexURL` from functions as well

js/bam/coverageTrack.js
The colorBy property is set in the config for BAMTrack and not in the
root object.
=> Fix baseMod colorBy in coverageTrack

js/igv-create.js
This path is followed only when client_id is provided as part of
`igv.createBrowser`, so people using the web app have not experienced
this issue yet, because the web app initializes the client directly.
=> Fix passing client_id to oauth token client

js/sample/sampleInfo.js
picked from #1844 
There is a regression on TrackView#renderSVGContext which errors out because of a missing SampleInfo#isInitialized(), I implemented it.
CC: @jrobinso
=> fix broken TrackView#renderSVGContext

js/browser.js
- This PR supports the fix to allow marking GTEx track menu tracks as selected/unselected.
-
=> Browser: Add getTrackConfigs() method. Returns list of JSON strings

js/feature/mergedTrack.js
Hello! First of all, thanks for all the work you've been putting into igv.js and all the new releases!!
One thing I noticed is a small bug in Merged Track popup which prevents it from displaying (see the screenshots).
This was probably partly introduced by myself not highlighting why I added a new parameter (trackNames) to the MergedFeatureCollection class when I previously worked on this. You've probably deleted it while cleaning the code but it is important for the popup data as it is used to display track names in the order of the actual tracks in the popup. I've reintroduced it and added a comment that should hopefully make it clearer.
Let me know if this breaks anything I am missing to see.
Edit: another side thing, we should perhaps think about updating eslint to newer version and …
=> Fix Merged track popup bug

js/htsget/htsgetBamReader.js
Potential fix for issue [1870](https://github.com/igvteam/igv.js/issues/1870) reported.
- add statements back into `bamUtils.js` that were present prior to the breakage.
- re-evaluates the header after the full fetch of data, to ensure the offset is correct for decoding
=> Fix htsget missing chrAliasTable and decoding header after data fetch

js/feature/wigTrack.js
Hello!
Another PR related to WIG tracks, this time related to log scale and negative values. As I've seen this has not been covered yet in either the JS or desktop version with negative values just being represented as 0. In my mind it makes sense to do the same thing as with the positive values and just represent it "under the line" i.e. as a negative value. I hope this makes sense to you as well.
The result can be seen in the screenshots below. 
This first set represents a merged track with two bigwig files which have opposite values
Regular scale:
Log scale:
This one is a single bigwig file with positive and negative values in it
Regular scale:
Log scale:
There was another minor fix related to accounting for y coordinates being 0 based which mostly influences the "line" style of the …
=> Add log scale feature to negative values in WIG track

js/roi/ROIManager.js
Hello a small bug fix which covers a scenario in which ideogram and/or ruler are hidden. ROIManager expects both of these when calculating the top margin but we can disable either of them in the config/options and that breaks the code.
Fixed with only ideogram
Fixed with only ruler
Fixed with no ruler and no ideogram
=> Fixed bug in ROI top margin when ideogram and/or ruler are hidden

js/roi/ROIManager.js, js/roi/ROIMenu.js, js/roi/ROISet.js
Hello, this PR fixes a bug related to deletion of (user defined) ROIs. As we've moved `roiSet` to the `menuItems` method of `ROIMenu` we can now directly delete the ROI in question as there was a bug in finding the exact ROI (and its set) a user selected. 
As can be seen in the video when a user defines a ROI over a ROI provided through config and then tries to delete it, the ROI provided through config gets deleted instead of the user defined one. In addition the ROI table was not being updated accordingly when a ROI is deleted.
https://github.com/user-attachments/assets/01fa0e01-1fac-4517-afae-59df281b42fd
=> Fix ROI deletion feature

js/bigwig/bwReader.js, js/bigwig/bwSource.js
Hi All, 
We would like to add to igv.js a none window function. 
This functionality is available for wig source and in IGV desktop. IGV Desktop screenshot:
Example from the example files:
=> BigWig track: Add none window Function

js/htsget/htsgetReader.js
Fixes #1908 :  HtsgetReader should not send HTSGet ticket server headers in data server requests
HtsgetReader should not include ticket server config / headers in requests to the data server. See issue #1908 for further details.
=> 1908 :  HtsgetReader should not send HTSGet ticket server headers in data server requests

js/feature/wigTrack.js, test/testWig.js
Hello All,
https://github.com/igvteam/igv.js/pull/1899 added none window function for wig track. However, it doesn't work with bedgraph format with error about `Unkown window function: None` when selecting "all" chromosome
This PR fixes it
=> fix none windowFunction for wig track in bedgraph format

js/gcnv/gcnvTrack.js
From [previous discussion](https://github.com/igvteam/igv.js/issues/1411), I remembered there being an option to disable pop up labels when clicking on non highlighted samples. This would be really useful where only a single highlighted sample is being displayed, but wanting to keep a full run of unlabelled and unhighlighted sample traces in grey to the background. I tried adding this to the bed file header but it did not seem to work.
I know this can be set via the track config when initialising the browser window, but this does not work when using things such as IGV web app for loading files.
Example header of file:
```
track type=gcnv height=500 onlyHandleClicksForHighlightedSamples=true highlight=sample_1;red highlight=mean;blue highlight=mean_plus_std;#0B2559 …
```
=> Bug fix for setting onlyHandleClicksForHighlightedSamples in gCNV track

js/cnvpytor/CombinedCaller.js, js/cnvpytor/GeneralUtil.js, js/cnvpytor/HDF5IndexedReader.js, js/cnvpytor/MeanShiftUtil.js, js/cnvpytor/baseCNVpytorVCF.js, js/cnvpytor/cnvpytorTrack.js, js/cnvpytor/cnvpytorVCF.js, js/vendor/lm-esm.js
The overall code structure for CNVpytor's track has been enhanced, and the following functionalities have been introduced in its VCF input:
1. Global Mean and Standard Deviation Calculation:
-   The `Levenberg-Marquardt` method is now used to calculate global mean and standard deviation.
-   A new file, `js/vendor/lm-esm.js`, has been added for this functionality, with the source referenced in the file.
2. GC correction has been implemented.
Thank you
-Arijit
=> CNVpytor Track: Improved Code and Added Features

js/ui/components/sliderDialog.js
I have added a precision option in the slide dialog, allowing a track to set the desired decimal precision. By default, it is set to 2.
```
this._precision = options.precision || 2; // Added precision option with a default value of 2
```
Previously, the precision was fixed at 2:
```
this._output.value = `${number.toFixed(2)}`;
```
Now, it dynamically adjusts based on the specified precision:
```
this._output.value = `${number.toFixed(this._precision)}`;
```
Thank you,
Arijit
=> Precision option for slide dialog

js/genome/genomeUtils.js
During the incremental update of `GenomeUtils.KNOWN_GENOMES`, the async function `igvxhr.loadJson` is being executed. This leads to a race condition if we create multiple IGV browsers.
=> fix race condition

js/igv.d.ts, js/trackViewport.js
Hello! A small PR aimed at the trackclick event and data available in the handler: **genomicLocation** has been added to the event handler for the **trackclick** event.
The reasoning behind this was mainly aimed at the bigwig tracks which can have a location range in the popup even though we click on a single location (a bigwig file can have ranges in it for example 100-200 23). I thought it might be useful having the exact location where the user clicked as this might be used in the handler itself. The new field was added as optional so we do not raise typing issues with current implementations users of igv.js might have. We could add the whole clickState as well but it seems to me that it would be an overkill.
Another fix I did while working on the above is related to the EvenReturn …
=> Add genomicLocation to the "trackclick" event

js/bam/alignmentTrack.js
* Use tag value if it is a color string for all tags, not just YC
=> * Bug fix - colorBy tag ignores supplied color string.  Fixes #1988
